### ISSUE TITLE
Error creating LazyReferenceField 

### ISSUE THREAD

**Issue by Aadi100** [idoshr/flask-mongoengine#11]
i have created  a lazy reference field in  the flask  and i am getting error for it. I have tried reading through the blogs but could not find or understand the solution. Below is the syntax I used to create the lazyreference field.

![Screenshot 2024-10-22 182505](https://github.com/user-attachments/assets/5cb8ce43-8541-42ed-a026-463d544a91e1)
  
` created_by = db.LazyReferenceField("User")`

This is the Error
`Exception has occurred: TypeError
WtfFieldMixin.__init__() takes 1 positional argument but 2 were given
  File "C:\Users\Hp\OneDrive\OFFICE WORK\AXIONICS ERP BACKEND\axionicsERP\generic\models.py", line 13, in Model
    created_by = db.LazyReferenceField("User")
TypeError: WtfFieldMixin.__init__() takes 1 positional argument but 2 were given`

Can someone tell me the correct syntax to use?

**Comment by idoshr** [comment]
Change this: 
` db.LazyReferenceField("User")`

to this:
`db.LazyReferenceField(document_type="User")`
